<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>9</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>PolyMatch3.Samples</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolyMatch3.Tools\PolyMatch3.Tools.csproj" />
  </ItemGroup>

</Project>
